### ISSUE TITLE
Does not load without an odysee account configured

### ISSUE THREAD

**Issue by Tank-Missile** [azzy9/plugin.video.lbryplus#1]
I tried using this addon, only to find it would not load and instead gives an error. I went into the settings and made an assumption that it was because an odysee account was not configured yet, and I was right. After configuring my account, the addon worked!

**Comment by azzy9** [comment]
Hi @Tank-Missile,
thanks for reporting this issue,
I shall have a look when I have time.

Sorry for the late reply,
for some strange reason Github didn't notify of this issue.

**Comment by azzy9** [comment]
Thanks again for reporting the issue.
I have Tested and fixed the issue.
It was a small error on my part.

I will close this issue, if you still encounter the issue, please can you re-open this issue :)
