### ISSUE TITLE
.webp thumbnail and posters not showing

### ISSUE THREAD

**Issue by azzy9** [azzy9/plugin.video.lbryplus#2]
This needs looking at.
Sometimes images and posters are not showing, this is due to them being .webp format
This is due to Kodi not supporting the format.

Maybe I could find a free service that will take the URL of webp files and convert them on the fly to jpeg.

**Comment by Andy-908** [comment]
many thanks for the great plugin to all involved! How about a URL to a conversion script to convert the posters on the fly in the future ? Then everyone could host a version of the script to convert the images on their own server.

**Comment by azzy9** [comment]
@Andy-908 Good idea, would you happen to know of any self hosted solutions?

**Comment by Andy-908** [comment]
Okay, i have set up something (for testing).  Hope this works. Just call the script and it should return the converted image as jpeg.

http://188.245.210.99/convert2jpg.php?url=https://<urlToImage>/image.webp

Can you use this in the plugin ?

**Comment by Slavegrid** [comment]
There is a similar fork of plugin.video.lbry hosted at https://slavegrid.com which contains a lot of fixes and additional functionality. To solve the thumbnail issue you can pass the URI to this function

`
def optimized_thumbnail_uri(uri: str, size: Union[tuple[int,int],None]=None, quality: Union[int,None]=None) -> str:
    s = 'https://thumbnails.odycdn.com/optimize/'
    if size:
        s += f's:{size[0]}:{size[1]}/'
    if quality:
        s += f'quality:{quality}/'
    return s + 'plain/' + uri

`

**Comment by azzy9** [comment]
@Andy-908 I have added an option for an image optimise service. since not all webp images have an file extension on them, I cannot just apply it to these. I have added a default URL for the service. If you want to use your own self hosted version, you could try and detect the image type and then convert it via PHP.
@Slavegrid thanks, I used the https://thumbnails.odycdn.com/optimize/ domain as the default setting.

**Comment by Andy-908** [comment]
Thanks a lot guys. Im still pretty new to Kodi. Whats the best way to get these changes into my installation ? Overwriting the changed file by hand ?

**Comment by azzy9** [comment]
released v0.7.0

**Comment by Andy-908** [comment]
Thank you azzy. Just saw and installed it. Works fantastic !
