### ISSUE TITLE
Does not load with odysee account configured and enabled

### ISSUE THREAD

**Issue by ohmichael** [azzy9/plugin.video.lbryplus#3]
I have checked the login and the login I put in is correct so that’s not why I’m getting errors when trying to enter the addon you have here and after 5 tries I have given up. Hope you can fix it.

**Comment by azzy9** [comment]
Hi @ohmichael,

Please can you post the error from the log as I am unable to reproduce this error.

**Comment by azzy9** [comment]
Also not sure what version of Kodi you are using, but this plugin is not Python2 compatible yet

**Comment by ohmichael** [comment]
Version 20.1 kodi on nvidia shield tv it’s fine though I guess I’ll use odysee on desktop web or iOS app and wait to others run into it through android kodi.
But I tried and it’s nothing on my end.

**Comment by azzy9** [comment]
No problem, I have tested on my android device with no issue. The only thing I can think of is that it may not like a special character you use in you password
